monorec/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    path('to_pdf/', include('to_pdf.urls',namespace='to_pdf')),


]

recipe/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('', views.home,name='home'),

    path('receptura/(<int:receptura_id>)',views.receptura,name='receptura'),
    path('receptura/formJson/<str:skl>/', views.formJson, name='formJson'),
    path('receptura/dodajskl/<str:sklId>/', views.dodajsklJson, name='dodajsklJson'),
    path('receptura/aktualizujTabela/<str:sklId>/', views.aktualizujTabela, name='aktualizujTabela'),
    path('receptura/delSkl/<int:id>/', views.delSkl, name='delSkl'),
    path('receptura/editFormJson/<str:skl>/', views.editFormJson, name='editformJson'),
    path('receptura/edytujskl/<str:pk>/', views.edytujsklJson, name='edytujsklJson'),
    path('dodajRecForm/', views.dodajRecForm, name='dodajRecForm'),
    path('receptura/dodajRecForm/', views.dodajRecForm, name='dodajRecForm'),
    path('dodawanieRecJson/', views.dodawanieRecJson, name='dodawanieRecJson'),
    path('receptura/dodawanieRecJson/', views.dodawanieRecJson, name='dodawanieRecJson'),
    path('receptura/obliczeniaOlCacJson/<str:sklId>/', views.obliczeniaOlCacJson, name='obliczeniaOlCac'),
    path('receptura/obliczeniaEtJson/<str:sklId>/', views.obliczeniaEtJson, name='obliczeniaEt'),
    path('aktualnaRec', views.aktualnaRec, name='aktualnaRec'),







]

to_pdf/urls.py
from . import views
from django.urls import path

app_name = 'to_pdf'
urlpatterns=[
path('<str:pk>/',views.to_pdf,name='to_pdf'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="shortcut icon" type="image/png" href="{% static 'mortar4.png' %}">
  <title> Twoja receptura</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inspiration&family=Roboto:wght@300;400&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Inspiration&family=Open+Sans:ital,wdth,wght@1,88.9,320&family=Roboto:wght@300;400&family=Trispace&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet"  href="{% static 'base.css' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'style.css' %}" />
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    {% block scripts %}

    {% endblock %}
<!--    <script src="{% static 'myjs.js' %}"></script>-->

    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Twoja receptura</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'aktualnaRec' %}" >Moja bieżąca receptura</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="dodajRecNavButton" data-target="#dodajRecModal" href="#dodajRecModal">Nowa receptura</a>
        </li>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Lista dostępnych składników  </a>
          <nav class="dropdown-menu" aria-labelledby="navbarDropdown" id="lista-dropdown"> </nav>

        </div>
        <li class="nav-item">
          <a class="nav-link" id="KontaktButton" data-target="#kontaktModal" href="#kontaktModal">Pomoc</a>
        </li>


      </ul>
      <ul>

      </ul>
      <img src="{% static 'mortar4.png' %}"/>

    </div>
  </div>
</nav>

<!-- Modal dodaj składnik -->

<div id="modalskladnik">

</div>

<div class="modal fade" id="dodajRecModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Podaj dane receptury</h5>
        <button type="button" class="close" id='close-x' data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body form-body-add">
<!--        place for form-->
          <form id="dodajRecModalBody" method="POST" class="form-modal">
              {% csrf_token %}

              <br>
          </form>
      </div>
      <div class="modal-footer">
        <input type="submit" id='dodajRecSubmit' class='btn btn-primary' value="Dodaj recepturę">

      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="kontaktModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" >
        <h5 class="modal-title" >Pomoc</h5>
        <button type="button" class="close-x" id ="close-x2" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="kontaktField">
        <p> dział w budowie</p>
<!--        <a href="https://www.youtube.com/@twoja.receptura" target="_blank">youtube: Twojareceptura</a>-->
      </div>
      <div class="modal-footer">


      </div>
    </div>
  </div>
</div>
<!-- Modal -->

{% block content %}


{% endblock content %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
<script src="{% static 'base.js' %}"> </script>

{% block js_files %} {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet"  href="{% static 'home.css' %}" />
<div class="container main-container">
    <br>
    <br>
    <div class="row my-row">

        <div class="col-6 my-col">
        <p class="main">    Witaj w internetowym kalkulatorze leków recepturowych.
            Aplikacja ma na celu ułatwienie określania ilości poszczególnych składników do wykonania leku.
        Główny nacisk został tutaj położony na najczęściej spotykane obliczenia etanolowe,witamin jak również masła kakaowego.
        Aplikacja ma charakter pomocniczy, wszystkie kalkulacje należy potwierdzić standardowymi obliczeniami.
        Zapraszam do pracy z twoja-receptura.
        </p></div>
        <div class="col-6 my-col" align="left">
            <img id='waga' src="{% static 'waga.png' %}"/>
<!--            <pre class="my-pre">-->
<!--                Kliknij poniżej aby dodać nową recepturę.-->
<!--                Pamiętaj ,że dodając nową recepturę nadpisujesz poprzednią.-->
<!--                -->
<!--            <a class="btn btn-primary btn-xl" data-target="#dodajRecModal" href="#dodajRecModal" onclick="openModal()" role="button"> Rozpocznij nową recepturę.  </a>-->
<!--              Kliknij poniżej aby wrócić do swojej ostatniej  receptury.-->
<!--            <a class="btn btn-primary btn-xl" href="{% url 'aktualnaRec' %}" role="button"> Wróć do swojej receptury. </a>-->
<!--            </pre>-->

        </div>
    </div>
    <br>
    <br>
    <br>
    <br>
    <div class="row my-row" id="button-row">
           <a class="btn btn-primary btn-xl" data-target="#dodajRecModal" href="#dodajRecModal" onclick="openModal()" role="button">  Rozpocznij nową recepturę.  </a>
            <a class="btn btn-primary btn-xl" href="{% url 'aktualnaRec' %}" role="button"> Wróć do swojej receptury. </a>

    </div>

</div>
<script>
    function openModal() {
        $("#dodajRecModal").modal('show')
    }
</script>

{% endblock content %}

templates/receptura.html
{% extends 'base.html' %}
{% load static %}



{% block content %}


<div class="container">
    <div class="row" >
            <div class="col">
                <div id='parametry' class="red mt-5"></div>
            </div>
        </div>
    <div class="row">
        <div class="col">
        <p id="p">

            <div class="nav-item dropdown">
          <a class=" btn btn-secondary mt-1 " href="#" id="wybor-dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Wybierz składnik z listy  </a>
          <nav class="dropdown-menu" aria-labelledby="navbarDropdown" id="wybor-skl-dropdown"> </nav>

        </div>
        </p>
            <span>lub</span>
        <form autocomplete="off" class="mt-5" id="dodaj-skladnk-form">
          <div class="autocomplete" style="width:250px;">
            <input id="myInput" type="text" name="myCountry" placeholder="Tu wpisz nazwę składnika" class="custom-input">
          </div>
        </form>
        <button type="submit" class="btn btn-secondary mt-1 " id="submitButton" > Dodaj składnik</button>

         <div id="tabela-docelowa" class="mt-5"></div>
               <br><br>

        <a class="btn btn-primary" id="toPdfButton" href="{% url 'to_pdf:to_pdf' receptura.pk %}"> do Pdf</a>
            </div>

        <div class="col">
            <div id='cards' class="red mt-5"></div>
        </div>
    </div>
    <div class="row">
        <div class="col">

        </div>




    </div>
</div>



<!--modal-->
<div id="modalskladnik">

</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalTitle">Modal title</h5>
        <button type="button" class="close" id='close-x-button' data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body form-body-add">
<!--        place for form-->
          <form id="modal-form" method="POST" class="form-modal">
              {% csrf_token %}

              <br>
          </form>
      </div>
      <div class="modal-footer">
          <button type="submit" id="zapiszzmianybutton"  class="btn btn-primary">Zapisz</button>
        <button type="submit" id="edytujjsklbutton"  class="btn btn-primary">Edytuj składnik</button>
        <button type="submit" id="dodajsklbutton"  class="btn btn-primary">Dodaj składnik</button>
        <button type="button" id='close-button' class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="zaDuzoSkladnikowModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="zaDuzoSkladnikowLabel">Przekroczona ilośc składników</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Maksymalna ilośc składników wynosi 10.
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="location.href='{% url 'home' %}'" >Przejdź do spisu twoich receptur</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- ModalEnd -->

<!-- Modal -->
<div class="modal fade" id="oblEtModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="id-modal-et-content">
      <div class="modal-header">
         Obliczenia Etanolu
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body" id="ol-et-text" style="width:0; float:left;" >

      </div>
      <div class="modal-footer">
        <!--<button class="btn btn-primary" onclick="window.print();" >Drukuj</button>-->
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- ModalEnd -->

<!-- Modal -->
<div class="modal fade" id="oblOlModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" id="id-modal-content">
      <div class="modal-header">
        Obliczenia Oleum Cacao
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <table id="dane" style="width: 100%;" >
            <tr>
    <th style="width: 20%;" >Składnik</th>
    <th style="width: 15%;" >masa składnika (g)</th>
    <th style="width: 20%;" >współczynnik wyparcia</th>
    <th style="width: 40%;" ></th>
  </tr>
            </table>
      <div class="modal-body obl-ol-class" id="ol-obl-text">
        Obliczenia Oleum Cacao
      </div>
      <div class="modal-footer">
<!--        <button class="btn btn-primary"  onclick="functionPrint()" data-dismiss="modal">Drukuj</button>-->
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- ModalEnd -->

<div id="pk-box" style=" display: none;">{{receptura.pk}}</div>



<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
<script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>

{% endblock  %}

{% block js_files %}
<script src="{% static 'myjs.js' %}"> </script>
{% endblock %}